apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: go-sample
  labels:
    app: go-sample
spec:
  template:
    metadata:
      labels:
        app: go-sample
    spec:
      containers:
      - image:  snowdeer/go-sample:latest
        name: go-sample
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8888
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: go-sample
  labels:
    app: go-sample
spec:
  ports:
  - name: go-sample-port1
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: go-sample-port2
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: go-sample
  type: LoadBalancer
---
apiVersion: v1
kind: Route
metadata:
  name: go-sample
  labels:
    app: go-sample
spec:
  port: 
    targetPort: go-sample-port1
  to:
    kind: Service
    name: go-sample
    weight: 100